### ISSUE TITLE
Missing documentation.

### ISSUE THREAD

**Issue by arunnbaba** [talmago/spacy_crfsuite#1]
Hi , I can see the potential of this project but it lacks clear documentation.

Can you please explain elaborately about how to train the model and the markdown example.

It's good work.

**Comment by arunnbaba** [comment]
Hi, So can you please elaborate on the process of training the model with Json files

**Comment by talmago** [comment]
@arunnbaba sure, i'll soon upload further documentation for training, including JSON and MD dataset example. On the meantime, you can take a look at this [test](https://github.com/talmago/spacy_crfsuite/blob/master/tests/test_markdown.py) which demonstrates the conversion from JSON to MD. 

Then, you can use the following command line to train the crf model on your examples; 

```
$ python -m spacy_crfsuite.trainer train train.json --model-dir model/
```

If you want to override the model hyper params you can use a config file from command line (i.e `-c config.json`).
Model parameters are described in [here](https://github.com/talmago/spacy_crfsuite/blob/master/spacy_crfsuite/crf_extractor.py#L32). Notice that currently it's not possible to configure CRF params except for the `L1_c`, `L2_c` and `max_iterations`. This should change in the future to allow all possible values for the crfsuite [estimator](https://github.com/TeamHG-Memex/sklearn-crfsuite/blob/master/sklearn_crfsuite/estimator.py#L22).

**Comment by arunnbaba** [comment]
Thanks for your reply

**Comment by talmago** [comment]
@arunnbaba See new [release](https://pypi.org/project/spacy-crfsuite/) for documentation. You can now use both command line and jupyter notebook to train / eval the CRF model. Hope this helps !

**Comment by arunnbaba** [comment]
Thank you for your quick actions and it helped me a lot in my work.

In the meantime if u have time look into my pandas_ui u might find it
useful in u r work.
