### ISSUE TITLE
Usage in Spacy 3.0

### ISSUE THREAD

**Issue by marzi-heidari** [talmago/spacy_crfsuite#8]
As adding custom pipelines is different in Spacy 3.0 from Spacy 2, can you add sample code for usage of this library in Spacy 3.0?

**Comment by talmago** [comment]
@annabeth-h spaCy 3.0 is not (yet) supported.

**Comment by fernandocamargoai** [comment]
Any plans to support it?

**Comment by elhele** [comment]
Any news? I could really use it for my current project.

**Comment by talmago** [comment]
@elhele although there is no official support for spacy 3.0, you can try the example [here](https://github.com/talmago/spacy_crfsuite#usage-as-a-spacy-pipeline-component) (many thanks @marzi-heidari for this).

**Comment by elhele** [comment]
@talmago it returns this error:

`AttributeError: 'spacy.tokens.span.Span' object has no attribute 'merge'
`

**Comment by talmago** [comment]
@elhele can you try to install from master (instead of PYPI) and report if it works? 

You can use this command (or just put the 3rd token in your requirements.txt)

```
pip install git+git://github.com/talmago/spacy_crfsuite.git@master
```

**Comment by elhele** [comment]
@talmago oh, great, it worked! Thank you so much  🙏

**Comment by talmago** [comment]
@elhele now that you verified it's working, i'm releasing v1.3.0 with spacy 3.0 support to PYPI. 

thanks again @marzi-heidari

**Comment by zachschillaci27** [comment]
Does the spacy 3.0 support extend to the config system? I am having difficulty implementing the CRF model within a config.cfg file to run from the spacy CLI.
